In [41]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Dense, LSTM, Dropout, Input
from tensorflow.keras.models import Model

In [42]:
df = pd.read_csv('/content/PRSA_data_2010.1.1-2014.12.31.csv')

In [43]:
for col in df.columns:
  print(col, df[col].unique())
  print()

No [    1     2     3 ... 43822 43823 43824]

year [2010 2011 2012 2013 2014]

month [ 1  2  3  4  5  6  7  8  9 10 11 12]

day [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31]

hour [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

pm2.5 [ nan 129. 148. 159. 181. 138. 109. 105. 124. 120. 132. 140. 152. 164.
 158. 154. 170. 149. 156. 126.  90.  63.  65.  55.  83.  91.  86.  82.
  78.  98. 107.  96.  95.  70.  61.  53.  71.  72.  76.  73.  79.  58.
  25.  26.  28.  20.  29.  27.  32.  30.  31.  33.  34.  36.  39.  41.
  50.  56.  59.  60.  84. 106.  66.  77.  44.  21.  42.  48.  49.  52.
  75.  93. 131. 127. 130.  43.  37.  24.  23.  40.  51.  57.  54.  67.
 198. 190. 210. 195. 275. 110. 100.  81.  92. 135. 155. 250. 200. 231.
 212. 219. 227. 226. 225. 168. 169. 165. 167. 196. 119.  45.  47.  62.
  35.  68.  88.  22.  17.  16.  18.  15.  13.   9.  11.  19.  12. 257.
 174. 161. 137.  64.  87.  89.  94.  69. 102. 141. 211. 242. 271. 249.
 147. 114. 108. 128. 150. 197. 235. 261. 269. 266. 263. 241. 205. 160.
 208. 209. 183. 182. 230. 172. 166. 177. 191. 268. 317. 291. 313. 282.
 303. 349. 407. 361. 234. 184. 146. 144. 173. 188. 203. 233. 408. 435.
 403. 360. 402. 358. 383. 332. 274. 256. 302. 330. 367. 297. 331. 323.
 339. 301. 310. 305. 336. 357. 485. 426. 374. 333. 343. 364. 389. 368.
 267.  38.  85. 199. 340. 298. 299. 300. 240. 213. 171. 153. 143.  14.
  10. 145. 101. 104.  97.  80. 121. 103.  99.  74. 189. 118. 125. 162.
 157. 178. 187. 185. 180. 136. 133. 163. 258. 247. 273. 253. 254. 229.
 193. 207. 176.   6.   8.   7.  46. 113. 259. 351. 980. 599. 116. 192.
 237. 115. 265. 236. 296. 117. 112. 204. 122. 175. 215. 214. 206. 220.
 111. 134. 142. 179. 218. 246. 264. 283. 223. 243. 262. 311. 307. 312.
 292. 353. 309. 284. 244. 139. 248. 123. 202. 224. 252. 222. 255.   5.
 216. 314. 201. 239. 228. 221. 217. 245. 232. 700. 473. 381. 315. 784.
 761. 260. 280. 366. 288. 194. 186. 286. 289. 285. 151. 385. 382. 369.
 342. 324. 272. 294.   4. 238. 251.   2.   3. 304. 290. 270. 278. 277.
 276. 281. 306. 295. 318. 326. 337. 321. 411. 414. 334. 455. 440. 293.
   1. 320. 372. 503. 534. 506. 505. 465. 468. 449. 418. 405. 388. 384.
 359. 355. 348. 344. 279. 287. 327. 365. 391. 423. 429. 439. 458. 436.
 431. 387. 350. 406. 422. 400. 470. 459. 378. 329. 335. 396. 412. 430.
 434. 438. 416. 417. 394. 380. 376. 397. 392. 428. 420. 399. 393. 415.
 395. 352. 419. 463. 481. 466. 479. 472. 467. 525. 504. 502. 521. 446.
 354. 362. 325. 346. 476. 480. 482. 535. 569. 562. 488. 453. 501. 559.
 557. 540. 371. 454. 328. 432. 433. 462. 398. 316. 379. 443. 322. 363.
 319. 308. 528. 489. 404. 410. 441. 425. 427. 474. 500. 548. 584. 607.
 611. 615. 587. 570. 573. 513. 345. 437. 477. 510. 526. 492. 527. 486.
 493. 515. 595. 563. 495. 508. 464. 452. 498. 478. 499. 494. 445. 457.
 347. 401. 373. 461. 421. 469. 409. 451. 424. 413. 377. 442. 375. 390.
 356. 341. 338. 386. 514. 370. 460. 490. 522. 456. 524. 491. 484. 450.
 558. 994. 972.   0. 529. 802. 845. 810. 776. 824. 886. 852. 858. 805.
 744. 731. 722. 684. 651. 673. 475. 523. 447. 448. 603. 496. 444. 512.
 532. 516. 541. 517. 539. 567. 659. 648. 671. 623. 618. 487. 579. 649.
 507. 545. 577. 483. 519. 551. 542. 580.]

DEWP [-21 -20 -19 -18 -17 -16 -15 -11  -7  -8  -9 -10 -12 -14 -22 -23 -24 -26
 -27 -25 -13  -5  -6  -4  -3  -2  -1   0   2   3   1   5   6   7   8   4
   9  10  11  13  15  16  17  18  14  12  19  20  21  22  23  24  25  26
  27  28 -28 -29 -31 -30 -32 -33 -35 -34 -36 -37 -39 -40 -38]

TEMP [-11.         -12.         -14.         -10.          -9.
  -8.          -7.          -5.          -3.          -2.
  -1.          -4.          -6.         -13.         -15.
 -17.         -18.         -19.         -16.           0.
   1.           2.           3.           4.           5.
   6.           8.           7.           9.          10.
  11.          12.          13.          14.          15.
  16.          17.          19.          20.          21.
  22.          18.          23.          24.          25.
  28.          31.          32.          29.          27.
  26.          30.          33.          34.          35.
  36.          37.          38.          39.          40.
  41.          42.          14.66666667   9.33333333]

PRES [1021.       1020.       1019.       1018.       1017.       1015.
 1014.       1016.       1022.       1023.       1024.       1025.
 1026.       1027.       1028.       1029.       1030.       1031.
 1032.       1033.       1034.       1035.       1036.       1037.
 1038.       1039.       1013.       1012.       1011.       1010.
 1009.       1008.       1007.       1006.       1004.       1003.
 1002.       1005.       1040.       1041.       1042.       1001.
 1000.        999.        997.        996.        998.        995.
  994.       1043.       1019.5      1029.666667 1032.333333 1044.
 1045.        993.        992.       1046.       1027.5       991.      ]

cbwd ['NW' 'cv' 'NE' 'SE']

Iws [  1.79   4.92   6.71 ... 242.7  246.72 249.85]

Is [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 15 16 17 19 20 21 22 23 24 25
 26 27 14 18]

Ir [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36]

In [44]:
df

          No  year  month  day  hour  pm2.5  ...  TEMP    PRES  cbwd     Iws  Is  Ir
0          1  2010      1    1     0    NaN  ... -11.0  1021.0    NW    1.79   0   0
1          2  2010      1    1     1    NaN  ... -12.0  1020.0    NW    4.92   0   0
2          3  2010      1    1     2    NaN  ... -11.0  1019.0    NW    6.71   0   0
3          4  2010      1    1     3    NaN  ... -14.0  1019.0    NW    9.84   0   0
4          5  2010      1    1     4    NaN  ... -12.0  1018.0    NW   12.97   0   0
...      ...   ...    ...  ...   ...    ...  ...   ...     ...   ...     ...  ..  ..
43819  43820  2014     12   31    19    8.0  ...  -2.0  1034.0    NW  231.97   0   0
43820  43821  2014     12   31    20   10.0  ...  -3.0  1034.0    NW  237.78   0   0
43821  43822  2014     12   31    21   10.0  ...  -3.0  1034.0    NW  242.70   0   0
43822  43823  2014     12   31    22    8.0  ...  -4.0  1034.0    NW  246.72   0   0
43823  43824  2014     12   31    23   12.0  ...  -3.0  1034.0    NW  249.85   0   0

[43824 rows x 13 columns]

In [45]:
df.drop(columns=['cbwd', 'No'], inplace = True)

In [46]:
df

       year  month  day  hour  pm2.5  DEWP  TEMP    PRES     Iws  Is  Ir
0      2010      1    1     0    NaN   -21 -11.0  1021.0    1.79   0   0
1      2010      1    1     1    NaN   -21 -12.0  1020.0    4.92   0   0
2      2010      1    1     2    NaN   -21 -11.0  1019.0    6.71   0   0
3      2010      1    1     3    NaN   -21 -14.0  1019.0    9.84   0   0
4      2010      1    1     4    NaN   -20 -12.0  1018.0   12.97   0   0
...     ...    ...  ...   ...    ...   ...   ...     ...     ...  ..  ..
43819  2014     12   31    19    8.0   -23  -2.0  1034.0  231.97   0   0
43820  2014     12   31    20   10.0   -22  -3.0  1034.0  237.78   0   0
43821  2014     12   31    21   10.0   -22  -3.0  1034.0  242.70   0   0
43822  2014     12   31    22    8.0   -22  -4.0  1034.0  246.72   0   0
43823  2014     12   31    23   12.0   -21  -3.0  1034.0  249.85   0   0

[43824 rows x 11 columns]

In [ ]:
df['pm2.5'] = df['pm2.5'].fillna(df['pm2.5'].mean())
display(df.head())

In [48]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
scaled_df = scalar.fit_transform(df.values)

In [49]:
def create_data(data, seq_len):
  x = []
  y = []
  for i in range(len(data) - seq_len):
    x.append(data[i:i+seq_len, : ])
    y.append(data[i+seq_len, 4])
  return np.array(x), np.array(y)

In [50]:
x, y = create_data(scaled_df, 24)

In [51]:
split_index = int(len(x)*0.8)
xtrain = x[:split_index]
xtest = x[split_index:]
ytrain = y[:split_index]
ytest = y[split_index:]

In [52]:
xtrain.shape

(35040, 24, 11)

In [53]:
D = 11
T = 24

In [54]:
def create_model(T, D):
  i = Input(shape = (T, D))
  x = LSTM(128, return_sequences = False)(i)
  x = Dropout(0.2)(x)
  x = Dense(32, activation='relu')(x)
  x = Dropout(0.2)(x)
  x = Dense(1)(x)

  return Model(i, x)

In [55]:
model = create_model(T, D)

In [56]:
from tensorflow.keras.optimizers import Adam

# Clip gradients so no single update exceeds 1.0
custom_adam = Adam(learning_rate=0.001, clipvalue=1.0)

model.compile(optimizer=custom_adam,
              loss='mse',
              metrics=['mae'])

In [57]:
r = model.fit(xtrain, ytrain, epochs = 100, batch_size = 32, validation_data = (xtest, ytest))

Epoch 1/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 0.1495 - mae: 0.2440 - val_loss: 0.0672 - val_mae: 0.1591
Epoch 2/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 0.1057 - mae: 0.1961 - val_loss: 0.0689 - val_mae: 0.1543
Epoch 3/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 0.1014 - mae: 0.1890 - val_loss: 0.0645 - val_mae: 0.1544
Epoch 4/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 0.0985 - mae: 0.1866 - val_loss: 0.0715 - val_mae: 0.1627
Epoch 5/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 0.0971 - mae: 0.1853 - val_loss: 0.0737 - val_mae: 0.1669
Epoch 6/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 0.0980 - mae: 0.1848 - val_loss: 0.0625 - val_mae: 0.1416
Epoch 7/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 0.0948 - mae: 0.1831 - val_loss: 0.0655 - val_mae: 0.1494
Epoch 8/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 0.0941 - mae: 0.1825 - val_loss: 0.0664 - val_mae: 0.1471
Epoch 9/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 0.0943 - mae: 0.1831 - val_loss: 0.0604 - val_mae: 0.1365
Epoch 10/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 0.0931 - mae: 0.1815 - val_loss: 0.0610 - val_mae: 0.1377
Epoch 11/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 0.0937 - mae: 0.1819 - val_loss: 0.0611 - val_mae: 0.1389
Epoch 12/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - loss: 0.0917 - mae: 0.1815 - val_loss: 0.0647 - val_mae: 0.1561
Epoch 13/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 0.0904 - mae: 0.1805 - val_loss: 0.0599 - val_mae: 0.1401
Epoch 14/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 0.0905 - mae: 0.1801 - val_loss: 0.0662 - val_mae: 0.1531
Epoch 15/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 0.0895 - mae: 0.1796 - val_loss: 0.0611 - val_mae: 0.1430
Epoch 16/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 0.0898 - mae: 0.1805 - val_loss: 0.0602 - val_mae: 0.1362
Epoch 17/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 0.0892 - mae: 0.1801 - val_loss: 0.0661 - val_mae: 0.1445
Epoch 18/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 0.0892 - mae: 0.1813 - val_loss: 0.0622 - val_mae: 0.1414
Epoch 19/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 0.0868 - mae: 0.1780 - val_loss: 0.0707 - val_mae: 0.1612
Epoch 20/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 0.0884 - mae: 0.1790 - val_loss: 0.0621 - val_mae: 0.1412
Epoch 21/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 0.0878 - mae: 0.1793 - val_loss: 0.0683 - val_mae: 0.1598
Epoch 22/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 0.0871 - mae: 0.1785 - val_loss: 0.0656 - val_mae: 0.1534
Epoch 23/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 0.0872 - mae: 0.1785 - val_loss: 0.0624 - val_mae: 0.1436
Epoch 24/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 0.0859 - mae: 0.1791 - val_loss: 0.0607 - val_mae: 0.1405
Epoch 25/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 0.0849 - mae: 0.1776 - val_loss: 0.0623 - val_mae: 0.1445
Epoch 26/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 0.0840 - mae: 0.1777 - val_loss: 0.0721 - val_mae: 0.1558
Epoch 27/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 0.0835 - mae: 0.1772 - val_loss: 0.0616 - val_mae: 0.1398
Epoch 28/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 0.0845 - mae: 0.1788 - val_loss: 0.0638 - val_mae: 0.1470
Epoch 29/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - loss: 0.0827 - mae: 0.1760 - val_loss: 0.0657 - val_mae: 0.1489
Epoch 30/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 0.0841 - mae: 0.1777 - val_loss: 0.0648 - val_mae: 0.1513
Epoch 31/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 0.0833 - mae: 0.1777 - val_loss: 0.0775 - val_mae: 0.1634
Epoch 32/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 0.0805 - mae: 0.1771 - val_loss: 0.0640 - val_mae: 0.1458
Epoch 33/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 0.0836 - mae: 0.1767 - val_loss: 0.0680 - val_mae: 0.1639
Epoch 34/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 0.0824 - mae: 0.1773 - val_loss: 0.0681 - val_mae: 0.1495
Epoch 35/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 0.0799 - mae: 0.1769 - val_loss: 0.0698 - val_mae: 0.1511
Epoch 36/100
1095/1095 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 0.0815 - mae: 0.1772 - val_loss: 0.0702 - val_mae: 0.1682
Epoch 37/100
1033/1095 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0796 - mae: 0.1755

KeyboardInterrupt: