In [4]:
import tensorflow as tf

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Dense, Input, GlobalMaxPooling1D
from tensorflow.keras.layers import LSTM, Embedding, TextVectorization
from tensorflow.keras.models import Model

In [7]:
!wget -nc https://lazyprogrammer.me/course_files/spam.csv

--2026-06-20 08:40:39--  https://lazyprogrammer.me/course_files/spam.csv
Resolving lazyprogrammer.me (lazyprogrammer.me)... 172.67.213.166, 104.21.23.210, 2606:4700:3030::ac43:d5a6, ...
Connecting to lazyprogrammer.me (lazyprogrammer.me)|172.67.213.166|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 503663 (492K) [text/csv]
Saving to: ‘spam.csv’

spam.csv            100%[===================>] 491.86K  1.99MB/s    in 0.2s

2026-06-20 08:40:39 (1.99 MB/s) - ‘spam.csv’ saved [503663/503663]

In [9]:
dataset = pd.read_csv("spam.csv", encoding='ISO-8859-1')

In [11]:
dataset.drop(["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"], axis=1, inplace=True)

In [12]:
dataset

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [13]:
dataset.columns = ['labels', 'data']

In [14]:
dataset

     labels                                               data
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham              Will Ì_ b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [15]:
dataset['labels'] = dataset['labels'].map({"ham":0, "spam":1})

In [16]:
y = dataset['labels'].values

In [17]:
y

array([0, 0, 1, ..., 0, 0, 0])

In [18]:
x = dataset.drop('labels', axis = 1)

In [19]:
x

                                                   data
0     Go until jurong point, crazy.. Available only ...
1                         Ok lar... Joking wif u oni...
2     Free entry in 2 a wkly comp to win FA Cup fina...
3     U dun say so early hor... U c already then say...
4     Nah I don't think he goes to usf, he lives aro...
...                                                 ...
5567  This is the 2nd time we have tried 2 contact u...
5568              Will Ì_ b going to esplanade fr home?
5569  Pity, * was in mood for that. So...any other s...
5570  The guy did some bitching but I acted like i'd...
5571                         Rofl. Its true to its name

[5572 rows x 1 columns]

In [20]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.33, random_state=42, stratify = y)

In [22]:
train_ds = tf.data.Dataset.from_tensor_slices((xtrain.values, ytrain))
test_ds = tf.data.Dataset.from_tensor_slices((xtest.values, ytest))

In [25]:
MAX_VOCAB_SIZE = 20000
vectorization = TextVectorization(max_tokens=MAX_VOCAB_SIZE)
vectorization.adapt(train_ds.map(lambda x, y: x))

In [29]:
vectorization.get_vocabulary()

['',
 '[UNK]',
 np.str_('to'),
 np.str_('i'),
 np.str_('you'),
 np.str_('a'),
 np.str_('the'),
 np.str_('u'),
 np.str_('and'),
 np.str_('is'),
 np.str_('in'),
 np.str_('my'),
 np.str_('me'),
 np.str_('your'),
 np.str_('for'),
 np.str_('of'),
 np.str_('it'),
 np.str_('have'),
 np.str_('call'),
 np.str_('on'),
 np.str_('that'),
 np.str_('im'),
 np.str_('are'),
 np.str_('now'),
 np.str_('so'),
 np.str_('2'),
 np.str_('but'),
 np.str_('not'),
 np.str_('do'),
 np.str_('can'),
 np.str_('at'),
 np.str_('or'),
 np.str_('ur'),
 np.str_('get'),
 np.str_('be'),
 np.str_('with'),
 np.str_('if'),
 np.str_('just'),
 np.str_('we'),
 np.str_('will'),
 np.str_('this'),
 np.str_('no'),
 np.str_('up'),
 np.str_('when'),
 np.str_('its'),
 np.str_('ltgt'),
 np.str_('go'),
 np.str_('free'),
 np.str_('dont'),
 np.str_('4'),
 np.str_('from'),
 np.str_('ok'),
 np.str_('know'),
 np.str_('what'),
 np.str_('out'),
 np.str_('how'),
 np.str_('all'),
 np.str_('got'),
 np.str_('ill'),
 np.str_('good'),
 np.str_('like'),
 np.str_('was'),
 np.str_('am'),
 np.str_('then'),
 np.str_('come'),
 np.str_('time'),
 np.str_('there'),
 np.str_('want'),
 np.str_('only'),
 np.str_('send'),
 np.str_('day'),
 np.str_('as'),
 np.str_('text'),
 np.str_('love'),
 np.str_('he'),
 np.str_('about'),
 np.str_('by'),
 np.str_('txt'),
 np.str_('one'),
 np.str_('home'),
 np.str_('going'),
 np.str_('our'),
 np.str_('need'),
 np.str_('stop'),
 np.str_('sorry'),
 np.str_('lor'),
 np.str_('reply'),
 np.str_('still'),
 np.str_('r'),
 np.str_('see'),
 np.str_('da'),
 np.str_('back'),
 np.str_('n'),
 np.str_('later'),
 np.str_('new'),
 np.str_('today'),
 np.str_('well'),
 np.str_('think'),
 np.str_('tell'),
 np.str_('hi'),
 np.str_('any'),
 np.str_('phone'),
 np.str_('take'),
 np.str_('please'),
 np.str_('cant'),
 np.str_('been'),
 np.str_('she'),
 np.str_('here'),
 np.str_('oh'),
 np.str_('some'),
 np.str_('night'),
 np.str_('dear'),
 np.str_('did'),
 np.str_('an'),
 np.str_('they'),
 np.str_('mobile'),
 np.str_('has'),
 np.str_('claim'),
 np.str_('pls'),
 np.str_('Ì'),
 np.str_('week'),
 np.str_('more'),
 np.str_('give'),
 np.str_('wat'),
 np.str_('hope'),
 np.str_('d'),
 np.str_('where'),
 np.str_('too'),
 np.str_('her'),
 np.str_('way'),
 np.str_('hey'),
 np.str_('had'),
 np.str_('great'),
 np.str_('much'),
 np.str_('him'),
 np.str_('thats'),
 np.str_('number'),
 np.str_('who'),
 np.str_('already'),
 np.str_('happy'),
 np.str_('tomorrow'),
 np.str_('work'),
 np.str_('right'),
 np.str_('should'),
 np.str_('really'),
 np.str_('message'),
 np.str_('were'),
 np.str_('make'),
 np.str_('yeah'),
 np.str_('e'),
 np.str_('doing'),
 np.str_('ask'),
 np.str_('why'),
 np.str_('msg'),
 np.str_('last'),
 np.str_('after'),
 np.str_('prize'),
 np.str_('babe'),
 np.str_('anything'),
 np.str_('amp'),
 np.str_('yes'),
 np.str_('over'),
 np.str_('miss'),
 np.str_('find'),
 np.str_('morning'),
 np.str_('ive'),
 np.str_('c'),
 np.str_('would'),
 np.str_('win'),
 np.str_('said'),
 np.str_('very'),
 np.str_('them'),
 np.str_('sure'),
 np.str_('something'),
 np.str_('sent'),
 np.str_('say'),
 np.str_('life'),
 np.str_('cos'),
 np.str_('cash'),
 np.str_('1'),
 np.str_('next'),
 np.str_('keep'),
 np.str_('care'),
 np.str_('place'),
 np.str_('lol'),
 np.str_('didnt'),
 np.str_('again'),
 np.str_('us'),
 np.str_('pick'),
 np.str_('let'),
 np.str_('also'),
 np.str_('won'),
 np.str_('thing'),
 np.str_('before'),
 np.str_('b'),
 np.str_('thanks'),
 np.str_('k'),
 np.str_('went'),
 np.str_('contact'),
 np.str_('urgent'),
 np.str_('nokia'),
 np.str_('late'),
 np.str_('buy'),
 np.str_('service'),
 np.str_('per'),
 np.str_('meet'),
 np.str_('friends'),
 np.str_('3'),
 np.str_('which'),
 np.str_('wan'),
 np.str_('tonight'),
 np.str_('someone'),
 np.str_('money'),
 np.str_('first'),
 np.str_('every'),
 np.str_('even'),
 np.str_('could'),
 np.str_('youre'),
 np.str_('wont'),
 np.str_('thought'),
 np.str_('his'),
 np.str_('gonna'),
 np.str_('feel'),
 np.str_('wish'),
 np.str_('v'),
 np.str_('off'),
 np.str_('wait'),
 np.str_('soon'),
 np.str_('name'),
 np.str_('many'),
 np.str_('ÌÏ'),
 np.str_('things'),
 np.str_('talk'),
 np.str_('chat'),
 np.str_('ya'),
 np.str_('sleep'),
 np.str_('may'),
 np.str_('dun'),
 np.str_('customer'),
 np.str_('waiting'),
 np.str_('same'),
 np.str_('nice'),
 np.str_('hello'),
 np.str_('getting'),
 np.str_('down'),
 np.str_('yet'),
 np.str_('x'),
 np.str_('try'),
 np.str_('told'),
 np.str_('smile'),
 np.str_('other'),
 np.str_('long'),
 np.str_('having'),
 np.str_('havent'),
 np.str_('gud'),
 np.str_('coming'),
 np.str_('always'),
 np.str_('16'),
 np.str_('tone'),
 np.str_('special'),
 np.str_('people'),
 np.str_('live'),
 np.str_('hows'),
 np.str_('help'),
 np.str_('class'),
 np.str_('year'),
 np.str_('mins'),
 np.str_('leave'),
 np.str_('y'),
 np.str_('use'),
 np.str_('than'),
 np.str_('stuff'),
 np.str_('person'),
 np.str_('lunch'),
 np.str_('holiday'),
 np.str_('friend'),
 np.str_('fine'),
 np.str_('around'),
 np.str_('trying'),
 np.str_('never'),
 np.str_('liao'),
 np.str_('draw'),
 np.str_('done'),
 np.str_('days'),
 np.str_('cool'),
 np.str_('being'),
 np.str_('yo'),
 np.str_('sms'),
 np.str_('ready'),
 np.str_('meeting'),
 np.str_('man'),
 np.str_('lot'),
 np.str_('guaranteed'),
 np.str_('enjoy'),
 np.str_('chance'),
 np.str_('better'),
 np.str_('because'),
 np.str_('6'),
 np.str_('thk'),
 np.str_('min'),
 np.str_('heart'),
 np.str_('half'),
 np.str_('haha'),
 np.str_('finish'),
 np.str_('18'),
 np.str_('yup'),
 np.str_('world'),
 np.str_('real'),
 np.str_('problem'),
 np.str_('job'),
 np.str_('easy'),
 np.str_('check'),
 np.str_('birthday'),
 np.str_('big'),
 np.str_('weekend'),
 np.str_('shows'),
 np.str_('room'),
 np.str_('princess'),
 np.str_('nothing'),
 np.str_('minutes'),
 np.str_('line'),
 np.str_('landline'),
 np.str_('end'),
 np.str_('eat'),
 np.str_('dat'),
 np.str_('car'),
 np.str_('box'),
 np.str_('bit'),
 np.str_('another'),
 np.str_('1st'),
 np.str_('whats'),
 np.str_('sir'),
 np.str_('offer'),
 np.str_('must'),
 np.str_('luv'),
 np.str_('guess'),
 np.str_('early'),
 np.str_('does'),
 np.str_('best'),
 np.str_('awarded'),
 np.str_('aight'),
 np.str_('account'),
 np.str_('true'),
 np.str_('those'),
 np.str_('theres'),
 np.str_('probably'),
 np.str_('play'),
 np.str_('pay'),
 np.str_('mind'),
 np.str_('might'),
 np.str_('kiss'),
 np.str_('fuck'),
 np.str_('few'),
 np.str_('enough'),
 np.str_('camera'),
 np.str_('bed'),
 np.str_('apply'),
 np.str_('5'),
 np.str_('watching'),
 np.str_('watch'),
 np.str_('video'),
 np.str_('two'),
 np.str_('tcs'),
 np.str_('sweet'),
 np.str_('shit'),
 np.str_('remember'),
 np.str_('receive'),
 np.str_('missing'),
 np.str_('made'),
 np.str_('look'),
 np.str_('jus'),
 np.str_('came'),
 np.str_('bad'),
 np.str_('å£1000'),
 np.str_('yesterday'),
 np.str_('wanna'),
 np.str_('until'),
 np.str_('texts'),
 np.str_('shopping'),
 np.str_('shall'),
 np.str_('sat'),
 np.str_('po'),
 np.str_('office'),
 np.str_('maybe'),
 np.str_('left'),
 np.str_('latest'),
 np.str_('lar'),
 np.str_('into'),
 np.str_('guys'),
 np.str_('god'),
 np.str_('dunno'),
 np.str_('dis'),
 np.str_('dinner'),
 np.str_('collection'),
 np.str_('collect'),
 np.str_('code'),
 np.str_('between'),
 np.str_('tv'),
 np.str_('speak'),
 np.str_('since'),
 np.str_('show'),
 np.str_('reach'),
 np.str_('plan'),
 np.str_('part'),
 np.str_('orange'),
 np.str_('once'),
 np.str_('most'),
 np.str_('mob'),
 np.str_('missed'),
 np.str_('means'),
 np.str_('important'),
 np.str_('house'),
 np.str_('guy'),
 np.str_('girl'),
 np.str_('ever'),
 np.str_('doesnt'),
 np.str_('den'),
 np.str_('asked'),
 np.str_('500'),
 np.str_('2nd'),
 np.str_('xxx'),
 np.str_('without'),
 np.str_('while'),
 np.str_('thanx'),
 np.str_('thank'),
 np.str_('test'),
 np.str_('stay'),
 np.str_('start'),
 np.str_('selected'),
 np.str_('put'),
 np.str_('plus'),
 np.str_('movie'),
 np.str_('hes'),
 np.str_('hear'),
 np.str_('gift'),
 np.str_('face'),
 np.str_('everything'),
 np.str_('evening'),
 np.str_('cost'),
 np.str_('baby'),
 np.str_('abt'),
 np.str_('å£150'),
 np.str_('years'),
 np.str_('xmas'),
 np.str_('working'),
 np.str_('word'),
 np.str_('wen'),
 np.str_('wake'),
 np.str_('till'),
 np.str_('school'),
 np.str_('quite'),
 np.str_('price'),
 np.str_('network'),
 np.str_('join'),
 np.str_('calls'),
 np.str_('called'),
 np.str_('bus'),
 np.str_('bring'),
 np.str_('boy'),
 np.str_('away'),
 np.str_('award'),
 np.str_('anyway'),
 np.str_('actually'),
 np.str_('7'),
 np.str_('150ppm'),
 np.str_('å£2000'),
 np.str_('wif'),
 np.str_('wanted'),
 np.str_('tried'),
 np.str_('town'),
 np.str_('todays'),
 np.str_('tmr'),
 np.str_('says'),
 np.str_('s'),
 np.str_('oso'),
 np.str_('month'),
 np.str_('leh'),
 np.str_('juz'),
 np.str_('ah'),
 np.str_('afternoon'),
 np.str_('able'),
 np.str_('9'),
 np.str_('å£100'),
 np.str_('weekly'),
 np.str_('wants'),
 np.str_('vouchers'),
 np.str_('trip'),
 np.str_('tot'),
 np.str_('though'),
 np.str_('tc'),
 np.str_('smiling'),
 np.str_('shop'),
 np.str_('shes'),
 np.str_('sexy'),
 np.str_('saw'),
 np.str_('sae'),
 np.str_('run'),
 np.str_('ringtone'),
 np.str_('mail'),
 np.str_('huh'),
 np.str_('hair'),
 np.str_('goes'),
 np.str_('forgot'),
 np.str_('feeling'),
 np.str_('else'),
 np.str_('details'),
 np.str_('dad'),
 np.str_('bt'),
 np.str_('answer'),
 np.str_('worry'),
 np.str_('update'),
 np.str_('tscs'),
 np.str_('times'),
 np.str_('til'),
 np.str_('sch'),
 np.str_('question'),
 np.str_('plz'),
 np.str_('old'),
 np.str_('noe'),
 np.str_('makes'),
 np.str_('ltdecimalgt'),
 np.str_('lose'),
 np.str_('looking'),
 np.str_('little'),
 np.str_('lets'),
 np.str_('hour'),
 np.str_('food'),
 np.str_('finished'),
 np.str_('family'),
 np.str_('entry'),
 np.str_('dude'),
 np.str_('driving'),
 np.str_('change'),
 np.str_('bored'),
 np.str_('alright'),
 np.str_('address'),
 np.str_('150p'),
 np.str_('å£5000'),
 np.str_('top'),
 np.str_('together'),
 np.str_('these'),
 np.str_('sad'),
 np.str_('poly'),
 np.str_('pics'),
 np.str_('pa'),
 np.str_('outside'),
 np.str_('okay'),
 np.str_('neva'),
 np.str_('music'),
 np.str_('lucky'),
 np.str_('lei'),
 np.str_('isnt'),
 np.str_('hurt'),
 np.str_('hot'),
 np.str_('hav'),
 np.str_('full'),
 np.str_('friendship'),
 np.str_('calling'),
 np.str_('book'),
 np.str_('believe'),
 np.str_('awesome'),
 np.str_('await'),
 np.str_('ard'),
 np.str_('100'),
 np.str_('yourself'),
 np.str_('yours'),
 np.str_('wot'),
 np.str_('words'),
 np.str_('wife'),
 np.str_('whatever'),
 np.str_('walk'),
 np.str_('voucher'),
 np.str_('unsubscribe'),
 np.str_('tones'),
 np.str_('thinking'),
 np.str_('sun'),
 np.str_('started'),
 np.str_('sis'),
 np.str_('saturday'),
 np.str_('re'),
 np.str_('rate'),
 np.str_('points'),
 np.str_('pain'),
 np.str_('order'),
 np.str_('open'),
 np.str_('needs'),
 np.str_('messages'),
 np.str_('lots'),
 np.str_('id'),
 np.str_('happened'),
 np.str_('haf'),
 np.str_('g'),
 np.str_('fun'),
 np.str_('eve'),
 np.str_('either'),
 np.str_('double'),
 np.str_('delivery'),
 np.str_('de'),
 np.str_('date'),
 np.str_('coz'),
 np.str_('company'),
 np.str_('comes'),
 np.str_('colour'),
 np.str_('close'),
 np.str_('both'),
 np.str_('bonus'),
 np.str_('86688'),
 np.str_('750'),
 np.str_('å£500'),
 np.str_('tho'),
 np.str_('taking'),
 np.str_('snow'),
 np.str_('smth'),
 np.str_('simple'),
 np.str_('second'),
 np.str_('saying'),
 np.str_('rite'),
 np.str_('read'),
 np.str_('quiz'),
 np.str_('private'),
 np.str_('post'),
 np.str_('okie'),
 np.str_('nt'),
 np.str_('news'),
 np.str_('minute'),
 np.str_('mah'),
 np.str_('log'),
 np.str_('knw'),
 np.str_('kind'),
 np.str_('hours'),
 np.str_('head'),
 np.str_('hard'),
 np.str_('hand'),
 np.str_('ha'),
 np.str_('goin'),
 np.str_('fucking'),
 np.str_('everyone'),
 np.str_('drive'),
 np.str_('decided'),
 np.str_('credit'),
 np.str_('content'),
 np.str_('choose'),
 np.str_('camcorder'),
 np.str_('brother'),
 np.str_('break'),
 np.str_('angry'),
 np.str_('8007'),
 np.str_('8'),
 np.str_('10'),
 np.str_('08000930705'),
 np.str_('å£250'),
 np.str_('youll'),
 np.str_('wrong'),
 np.str_('wow'),
 np.str_('wkly'),
 np.str_('wk'),
 np.str_('wil'),
 np.str_('wid'),
 np.str_('welcome'),
 np.str_('valued'),
 np.str_('valid'),
 np.str_('used'),
 np.str_('uk'),
 np.str_('txts'),
 np.str_('touch'),
 np.str_('took'),
 np.str_('tel'),
 np.str_('takes'),
 np.str_('story'),
 np.str_('statement'),
 np.str_('sounds'),
 np.str_('side'),
 np.str_('savamob'),
 np.str_('ring'),
 np.str_('pounds'),
 np.str_('pobox'),
 np.str_('player'),
 np.str_('pic'),
 np.str_('phones'),
 np.str_('online'),
 np.str_('mrng'),
 np.str_('meant'),
 np.str_('mean'),
 np.str_('march'),
 np.str_('lovely'),
 np.str_('lost'),
 np.str_('listen'),
 np.str_('lesson'),
 np.str_('information'),
 np.str_('hee'),
 np.str_('happen'),
 np.str_('girls'),
 np.str_('games'),
 np.str_('game'),
 np.str_('fr'),
 np.str_('forget'),
 np.str_('final'),
 np.str_('feels'),
 np.str_('each'),
 np.str_('drop'),
 np.str_('dreams'),
 np.str_('congratulations'),
 np.str_('college'),
 np.str_('club'),
 np.str_('cause'),
 np.str_('card'),
 np.str_('boytoy'),
 np.str_('auction'),
 np.str_('alone'),
 np.str_('ago'),
 np.str_('aft'),
 np.str_('10p'),
 np.str_('yar'),
 np.str_('worth'),
 np.str_('within'),
 np.str_('whole'),
 np.str_('weeks'),
 np.str_('wats'),
 np.str_('w'),
 np.str_('visit'),
 np.str_('unredeemed'),
 np.str_('unlimited'),
 np.str_('tomo'),
 np.str_('through'),
 np.str_('surprise'),
 np.str_('small'),
 np.str_('sleeping'),
 np.str_('sister'),
 np.str_('services'),
 np.str_('seeing'),
 np.str_('reading'),
 np.str_('pretty'),
 np.str_('point'),
 np.str_('pm'),
 np.str_('pass'),
 np.str_('parents'),
 np.str_('numbers'),
 np.str_('nope'),
 np.str_('mom'),
 np.str_('mobileupd8'),
 np.str_('mine'),
 np.str_('mate'),
 np.str_('ltd'),
 np.str_('loving'),
 np.str_('light'),
 np.str_('leaving'),
 np.str_('identifier'),
 np.str_('hmv'),
 np.str_('gr8'),
 np.str_('goodmorning'),
 np.str_('gone'),
 np.str_('frnd'),
 np.str_('finally'),
 np.str_('far'),
 np.str_('expires'),
 np.str_('etc'),
 np.str_('eg'),
 np.str_('earlier'),
 np.str_('dnt'),
 np.str_('direct'),
 np.str_('del'),
 np.str_('dating'),
 np.str_('cs'),
 np.str_('crazy'),
 np.str_('course'),
 np.str_('correct'),
 np.str_('congrats'),
 np.str_('confirm'),
 np.str_('christmas'),
 np.str_('charge'),
 np.str_('case'),
 np.str_('busy'),
 np.str_('blue'),
 np.str_('beautiful'),
 np.str_('bank'),
 np.str_('b4'),
 np.str_('available'),
 np.str_('attempt'),
 np.str_('ass'),
 np.str_('almost'),
 np.str_('\x89ÛÒ'),
 np.str_('\x89Û'),
 np.str_('yr'),
 np.str_('youve'),
 np.str_('write'),
 np.str_('wonderful'),
 np.str_('wit'),
 np.str_('winner'),
 np.str_('wasnt'),
 np.str_('wana'),
 np.str_('ugh'),
 np.str_('type'),
 np.str_('their'),
 np.str_('telling'),
 np.str_('st'),
 np.str_('sort'),
 np.str_('song'),
 np.str_('sex'),
 np.str_('set'),
 np.str_('seen'),
 np.str_('secret'),
 np.str_('search'),
 np.str_('sea'),
 np.str_('rental'),
 np.str_('reason'),
 np.str_('questions'),
 np.str_('prob'),
 np.str_('party'),
 np.str_('park'),
 np.str_('paper'),
 np.str_('own'),
 np.str_('opt'),
 np.str_('operator'),
 np.str_('offers'),
 np.str_('mu'),
 np.str_('msgs'),
 np.str_('mr'),
 np.str_('making'),
 np.str_('m'),
 np.str_('luck'),
 np.str_('less'),
 np.str_('leaves'),
 np.str_('land'),
 np.str_('knows'),
 np.str_('kate'),
 np.str_('invited'),
 np.str_('hold'),
 np.str_('gas'),
 np.str_('frnds'),
 np.str_('fri'),
 np.str_('found'),
 np.str_('forever'),
 np.str_('fone'),
 np.str_('fast'),
 np.str_('fantastic'),
 np.str_('enter'),
 np.str_('ends'),
 np.str_('drugs'),
 np.str_('drink'),
 np.str_('download'),
 np.str_('don'),
 np.str_('difficult'),
 np.str_('die'),
 np.str_('cut'),
 np.str_('currently'),
 np.str_('couple'),
 np.str_('computer'),
 np.str_('chennai'),
 np.str_('charity'),
 np.str_('carlos'),
 np.str_('bslvyl'),
 np.str_('ans'),
 np.str_('against'),
 np.str_('87066'),
 np.str_('150pmsg'),
 np.str_('0800'),
 np.str_('å£350'),
 np.str_('weekends'),
 np.str_('wed'),
 np.str_('user'),
 np.str_('truth'),
 np.str_('tickets'),
 np.str_('thinkin'),
 np.str_('th'),
 np.str_('ten'),
 np.str_('tampa'),
 np.str_('talking'),
 np.str_('t'),
 np.str_('support'),
 np.str_('stupid'),
 np.str_('studying'),
 np.str_('somewhere'),
 np.str_('slept'),
 np.str_('situation'),
 np.str_('sitting'),
 np.str_('sick'),
 np.str_('shower'),
 np.str_('sending'),
 np.str_('semester'),
 np.str_('self'),
 np.str_('save'),
 np.str_('reward'),
 np.str_('remove'),
 np.str_('reaching'),
 np.str_('rates'),
 np.str_('project'),
 np.str_('power'),
 np.str_('picking'),
 np.str_('picked'),
 np.str_('pc'),
 np.str_('oredi'),
 np.str_('omg'),
 np.str_('none'),
 np.str_('nite'),
 np.str_('national'),
 np.str_('na'),
 np.str_('myself'),
 np.str_('mum'),
 np.str_('motorola'),
 np.str_('months'),
 np.str_('mode'),
 np.str_('mobiles'),
 np.str_('men'),
 np.str_('medical'),
 np.str_('mayb'),
 np.str_('lovable'),
 np.str_('loads'),
 np.str_('least'),
 np.str_('laptop'),
 np.str_('knew'),
 np.str_('india'),
 np.str_('immediately'),
 np.str_('hmm'),
 np.str_('gym'),
 np.str_('gotta'),
 np.str_('glad'),
 np.str_('gettin'),
 np.str_('friday'),
 np.str_('freemsg'),
 np.str_('film'),
 np.str_('felt'),
 np.str_('father'),
 np.str_('fancy'),
 np.str_('fact'),
 np.str_('eyes'),
 np.str_('entered'),
 np.str_('em'),
 np.str_('dream'),
 np.str_('discount'),
 np.str_('darlin'),
 np.str_('complimentary'),
 np.str_('charged'),
 np.str_('brings'),
 np.str_('bout'),
 np.str_('booked'),
 np.str_('bday'),
 np.str_('awaiting'),
 np.str_('anyone'),
 np.str_('age'),
 np.str_('87077'),
 np.str_('800'),
 np.str_('2003'),
 np.str_('150'),
 np.str_('12hrs'),
 np.str_('12'),
 np.str_('11'),
 np.str_('08000839402'),
 np.str_('yahoo'),
 np.str_('xy'),
 np.str_('xx'),
 np.str_('wun'),
 np.str_('workin'),
 np.str_('wondering'),
 np.str_('woke'),
 np.str_('wine'),
 np.str_('whenever'),
 np.str_('water'),
 np.str_('voice'),
 np.str_('via'),
 np.str_('valentine'),
 np.str_('urself'),
 np.str_('txting'),
 np.str_('tired'),
 np.str_('tht'),
 np.str_('thinks'),
 np.str_('terms'),
 np.str_('supposed'),
 np.str_('sunshine'),
 np.str_('sunday'),
 np.str_('sucks'),
 np.str_('study'),
 np.str_('south'),
 np.str_('sometimes'),
 np.str_('somebody'),
 np.str_('sol'),
 np.str_('slow'),
 np.str_('sk38xh'),
 np.str_('silent'),
 np.str_('sign'),
 np.str_('seriously'),
 np.str_('sell'),
 np.str_('safe'),
 np.str_('round'),
 np.str_('rent'),
 np.str_('registered'),
 np.str_('reached'),
 np.str_('pub'),
 np.str_('promise'),
 np.str_('press'),
 np.str_('pound'),
 np.str_('poor'),
 np.str_('polys'),
 np.str_('plans'),
 np.str_('paying'),
 np.str_('otherwise'),
 np.str_('others'),
 np.str_('orchard'),
 np.str_('onto'),
 np.str_('ones'),
 np.str_('o'),
 ...]

In [27]:
train_ds = train_ds.shuffle(10000).batch(32).prefetch(tf.data.AUTOTUNE)
test_ds = test_ds.batch(32).prefetch(tf.data.AUTOTUNE)

In [31]:
V = len(vectorization.get_vocabulary())
D = 64   # embedding dimensionality
M = 256   # number of hidden states
i = Input(shape=(1,), dtype=tf.string)
x = vectorization(i)
x = Embedding(V, D)(x)
x = LSTM(M, return_sequences=True)(x)
x = GlobalMaxPooling1D()(x)
x = Dense(1, activation='sigmoid')(x)
model = Model(i, x)

In [32]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [33]:
model.fit(train_ds, epochs=10, validation_data = test_ds)

Epoch 1/10
117/117 ━━━━━━━━━━━━━━━━━━━━ 27s 206ms/step - accuracy: 0.8768 - loss: 0.3253 - val_accuracy: 0.9636 - val_loss: 0.1562
Epoch 2/10
117/117 ━━━━━━━━━━━━━━━━━━━━ 23s 197ms/step - accuracy: 0.9153 - loss: 0.2108 - val_accuracy: 0.9260 - val_loss: 0.2094
Epoch 3/10
117/117 ━━━━━━━━━━━━━━━━━━━━ 21s 177ms/step - accuracy: 0.9523 - loss: 0.1516 - val_accuracy: 0.9668 - val_loss: 0.1160
Epoch 4/10
117/117 ━━━━━━━━━━━━━━━━━━━━ 23s 194ms/step - accuracy: 0.9775 - loss: 0.0885 - val_accuracy: 0.9690 - val_loss: 0.1050
Epoch 5/10
117/117 ━━━━━━━━━━━━━━━━━━━━ 23s 198ms/step - accuracy: 0.9855 - loss: 0.0628 - val_accuracy: 0.9788 - val_loss: 0.0942
Epoch 6/10
117/117 ━━━━━━━━━━━━━━━━━━━━ 21s 177ms/step - accuracy: 0.9890 - loss: 0.0438 - val_accuracy: 0.9821 - val_loss: 0.0707
Epoch 7/10
117/117 ━━━━━━━━━━━━━━━━━━━━ 22s 191ms/step - accuracy: 0.9968 - loss: 0.0180 - val_accuracy: 0.9831 - val_loss: 0.0843
Epoch 8/10
117/117 ━━━━━━━━━━━━━━━━━━━━ 22s 189ms/step - accuracy: 0.9979 - loss: 0.0120 - val_accuracy: 0.9853 - val_loss: 0.0698
Epoch 9/10
117/117 ━━━━━━━━━━━━━━━━━━━━ 21s 177ms/step - accuracy: 0.9981 - loss: 0.0117 - val_accuracy: 0.9837 - val_loss: 0.0779
Epoch 10/10
117/117 ━━━━━━━━━━━━━━━━━━━━ 36s 305ms/step - accuracy: 0.9989 - loss: 0.0051 - val_accuracy: 0.9848 - val_loss: 0.0881

In [34]:
from sklearn.metrics import f1_score

In [40]:
f1_score(ytest, model.predict(xtest['data'].values) > 0.5)

58/58 ━━━━━━━━━━━━━━━━━━━━ 4s 70ms/step

0.9423868312757202

In [43]:
xtest.data.values

array(["I'll be late...",
       'Wat makes some people dearer is not just de happiness dat u feel when u meet them but de pain u feel when u miss dem!!!',
       'Remember all those whom i hurt during days of satanic imposter in me.need to pay a price,so be it.may destiny keep me going and as u said pray that i get the mind to get over the same.',
       ...,
       "Sir, I need Velusamy sir's date of birth and company bank facilities details.",
       'Customer Loyalty Offer:The NEW Nokia6650 Mobile from ONLY å£10 at TXTAUCTION! Txt word: START to No: 81151 & get yours Now! 4T&Ctxt TC 150p/MTmsg',
       'Alright took the morphine. Back in yo.'], dtype=object)