In [26]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [27]:
dataset = pd.read_csv('/content/train.csv')

In [28]:
dataset

,id,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,...,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
0,0,Loamy,4.92,32.58,1.01,3.05,15.01,50.61,725.99,5.90,...,Sugarcane,Sowing,Zaid,Drip,Rainwater,0.82,No,112.16,East,Low
1,1,Clay,7.08,56.61,0.44,2.00,22.92,67.86,985.66,6.98,...,Wheat,Vegetative,Kharif,Rainfed,River,5.27,Yes,47.16,South,Low
2,2,Clay,5.69,27.71,0.81,2.83,26.97,92.22,2201.70,6.05,...,Rice,Vegetative,Kharif,Sprinkler,Reservoir,8.24,Yes,110.38,North,Low
3,3,Sandy,5.65,13.32,1.33,0.87,13.32,61.57,1357.33,9.12,...,Wheat,Flowering,Kharif,Canal,River,8.32,Yes,53.85,South,Medium
4,4,Clay,7.96,59.14,0.38,0.96,20.22,91.11,1538.20,6.95,...,Wheat,Sowing,Rabi,Canal,River,7.37,No,93.19,South,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629995,629995,Clay,6.54,13.45,1.15,1.86,26.65,26.86,1041.33,10.62,...,Rice,Sowing,Kharif,Sprinkler,River,4.35,No,118.36,South,Medium
629996,629996,Clay,7.03,54.49,0.96,2.35,36.99,88.00,1419.57,9.93,...,Sugarcane,Vegetative,Kharif,Drip,Groundwater,12.97,Yes,40.75,Central,Medium
629997,629997,Clay,6.52,11.98,0.93,0.38,37.82,70.98,88.45,8.19,...,Potato,Vegetative,Zaid,Canal,Reservoir,13.58,Yes,2.62,South,High
629998,629998,Clay,5.93,42.86,0.33,3.39,34.99,94.58,2433.92,9.88,...,Sugarcane,Vegetative,Zaid,Sprinkler,Groundwater,0.79,Yes,90.00,East,Low
629999,629999,Loamy,7.02,35.36,1.19,0.46,26.92,64.33,1269.55,7.91,...,Maize,Harvest,Kharif,Drip,Reservoir,3.80,No,112.93,West,Low

In [29]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 630000 entries, 0 to 629999
Data columns (total 21 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id                       630000 non-null  int64
 1   Soil_Type                630000 non-null  object
 2   Soil_pH                  630000 non-null  float64
 3   Soil_Moisture            630000 non-null  float64
 4   Organic_Carbon           630000 non-null  float64
 5   Electrical_Conductivity  630000 non-null  float64
 6   Temperature_C            630000 non-null  float64
 7   Humidity                 630000 non-null  float64
 8   Rainfall_mm              630000 non-null  float64
 9   Sunlight_Hours           630000 non-null  float64
 10  Wind_Speed_kmh           630000 non-null  float64
 11  Crop_Type                630000 non-null  object
 12  Crop_Growth_Stage        630000 non-null  object
 13  Season                   630000 non-null  object
 14  Irrigation_Type          630000 non-null  object
 15  Water_Source             630000 non-null  object
 16  Field_Area_hectare       630000 non-null  float64
 17  Mulching_Used            630000 non-null  object
 18  Previous_Irrigation_mm   630000 non-null  float64
 19  Region                   630000 non-null  object
 20  Irrigation_Need          630000 non-null  object
dtypes: float64(11), int64(1), object(9)
memory usage: 100.9+ MB

In [30]:
dataset.describe()

,id,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Field_Area_hectare,Previous_Irrigation_mm
count,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000
mean,314999.500000,6.482497,37.304482,0.922858,1.744605,26.998166,61.563180,1462.207566,7.513382,10.375394,7.517745,62.318177
std,181865.479132,0.922504,16.377082,0.365808,0.952321,8.623621,19.708152,612.989738,1.999322,5.689458,4.218124,34.246939
min,0.000000,4.800000,8.000000,0.300000,0.100000,12.000000,25.000000,0.380000,4.000000,0.500000,0.300000,0.020000
25%,157499.750000,5.690000,23.340000,0.610000,0.930000,19.517500,45.390000,954.570000,5.760000,5.280000,3.880000,33.140000
50%,314999.500000,6.440000,37.750000,0.910000,1.740000,26.960000,61.650000,1467.160000,7.580000,10.480000,7.380000,61.150000
75%,472499.250000,7.270000,51.270000,1.220000,2.580000,34.540000,79.120000,2054.280000,9.250000,15.430000,11.140000,92.690000
max,629999.000000,8.200000,64.990000,1.600000,3.500000,42.000000,94.990000,2499.690000,11.000000,20.000000,15.000000,119.990000

In [31]:
dataset = dataset.drop(['id'], axis = 1)

In [32]:
dataset

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
0,Loamy,4.92,32.58,1.01,3.05,15.01,50.61,725.99,5.90,16.79,Sugarcane,Sowing,Zaid,Drip,Rainwater,0.82,No,112.16,East,Low
1,Clay,7.08,56.61,0.44,2.00,22.92,67.86,985.66,6.98,3.39,Wheat,Vegetative,Kharif,Rainfed,River,5.27,Yes,47.16,South,Low
2,Clay,5.69,27.71,0.81,2.83,26.97,92.22,2201.70,6.05,3.85,Rice,Vegetative,Kharif,Sprinkler,Reservoir,8.24,Yes,110.38,North,Low
3,Sandy,5.65,13.32,1.33,0.87,13.32,61.57,1357.33,9.12,2.31,Wheat,Flowering,Kharif,Canal,River,8.32,Yes,53.85,South,Medium
4,Clay,7.96,59.14,0.38,0.96,20.22,91.11,1538.20,6.95,13.94,Wheat,Sowing,Rabi,Canal,River,7.37,No,93.19,South,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629995,Clay,6.54,13.45,1.15,1.86,26.65,26.86,1041.33,10.62,18.85,Rice,Sowing,Kharif,Sprinkler,River,4.35,No,118.36,South,Medium
629996,Clay,7.03,54.49,0.96,2.35,36.99,88.00,1419.57,9.93,17.99,Sugarcane,Vegetative,Kharif,Drip,Groundwater,12.97,Yes,40.75,Central,Medium
629997,Clay,6.52,11.98,0.93,0.38,37.82,70.98,88.45,8.19,17.25,Potato,Vegetative,Zaid,Canal,Reservoir,13.58,Yes,2.62,South,High
629998,Clay,5.93,42.86,0.33,3.39,34.99,94.58,2433.92,9.88,5.00,Sugarcane,Vegetative,Zaid,Sprinkler,Groundwater,0.79,Yes,90.00,East,Low
629999,Loamy,7.02,35.36,1.19,0.46,26.92,64.33,1269.55,7.91,2.72,Maize,Harvest,Kharif,Drip,Reservoir,3.80,No,112.93,West,Low

In [33]:
for column in dataset.columns:
  if dataset[column].dtype == 'object':
    print(column, ' : ', dataset[column].unique() , '      Different values: ' , len(dataset[column].unique()))

Soil_Type  :  ['Loamy' 'Clay' 'Sandy' 'Silt']       Different values:  4
Crop_Type  :  ['Sugarcane' 'Wheat' 'Rice' 'Potato' 'Cotton' 'Maize']       Different values:  6
Crop_Growth_Stage  :  ['Sowing' 'Vegetative' 'Flowering' 'Harvest']       Different values:  4
Season  :  ['Zaid' 'Kharif' 'Rabi']       Different values:  3
Irrigation_Type  :  ['Drip' 'Rainfed' 'Sprinkler' 'Canal']       Different values:  4
Water_Source  :  ['Rainwater' 'River' 'Reservoir' 'Groundwater']       Different values:  4
Mulching_Used  :  ['No' 'Yes']       Different values:  2
Region  :  ['East' 'South' 'North' 'West' 'Central']       Different values:  5
Irrigation_Need  :  ['Low' 'Medium' 'High']       Different values:  3

In [34]:
dataset['Mulching_Used'] = dataset['Mulching_Used'].map({'No':0, 'Yes':1})
dataset['Irrigation_Need'] = dataset['Irrigation_Need'].map({'Low': 0, 'Medium':1, 'High':2})

In [35]:
x = dataset.drop(['Irrigation_Need'], axis = 1)
y = dataset['Irrigation_Need']

In [66]:
y

0         0
1         0
2         0
3         1
4         0
         ..
629995    1
629996    1
629997    2
629998    0
629999    0
Name: Irrigation_Need, Length: 630000, dtype: int64

In [36]:
categorical_cols = []
for column in dataset.columns:
  if dataset[column].dtype == 'object':
    categorical_cols.append(column)

In [37]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(
    transformers=[
        ('onehotencoder', OneHotEncoder(drop='first', sparse_output=False), categorical_cols),
    ]
    , remainder='passthrough'
)

In [38]:
encoded_values = ct.fit_transform(x)
encoded_columns = ct.get_feature_names_out()
encoded_dataset = pd.DataFrame(encoded_values, columns=encoded_columns)

In [39]:
encoded_dataset

,onehotencoder__Soil_Type_Loamy,onehotencoder__Soil_Type_Sandy,onehotencoder__Soil_Type_Silt,onehotencoder__Crop_Type_Maize,onehotencoder__Crop_Type_Potato,onehotencoder__Crop_Type_Rice,onehotencoder__Crop_Type_Sugarcane,onehotencoder__Crop_Type_Wheat,onehotencoder__Crop_Growth_Stage_Harvest,onehotencoder__Crop_Growth_Stage_Sowing,...,remainder__Organic_Carbon,remainder__Electrical_Conductivity,remainder__Temperature_C,remainder__Humidity,remainder__Rainfall_mm,remainder__Sunlight_Hours,remainder__Wind_Speed_kmh,remainder__Field_Area_hectare,remainder__Mulching_Used,remainder__Previous_Irrigation_mm
0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,1.01,3.05,15.01,50.61,725.99,5.90,16.79,0.82,0.0,112.16
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.44,2.00,22.92,67.86,985.66,6.98,3.39,5.27,1.0,47.16
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.81,2.83,26.97,92.22,2201.70,6.05,3.85,8.24,1.0,110.38
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.33,0.87,13.32,61.57,1357.33,9.12,2.31,8.32,1.0,53.85
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.38,0.96,20.22,91.11,1538.20,6.95,13.94,7.37,0.0,93.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629995,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1.15,1.86,26.65,26.86,1041.33,10.62,18.85,4.35,0.0,118.36
629996,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.96,2.35,36.99,88.00,1419.57,9.93,17.99,12.97,1.0,40.75
629997,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.93,0.38,37.82,70.98,88.45,8.19,17.25,13.58,1.0,2.62
629998,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.33,3.39,34.99,94.58,2433.92,9.88,5.00,0.79,1.0,90.00
629999,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.19,0.46,26.92,64.33,1269.55,7.91,2.72,3.80,0.0,112.93

In [41]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(encoded_dataset, y, test_size=0.2, random_state=42, stratify=y)

In [42]:
from sklearn.ensemble import RandomForestClassifier

In [51]:
model = RandomForestClassifier(n_estimators=200)
model.fit(xtrain, ytrain)

KeyboardInterrupt:

In [44]:
from sklearn.metrics import accuracy_score
accuracy_score(model.predict(xtest), ytest)

0.9846507936507937

In [48]:
model_tf = tf.keras.models.Sequential([
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
])

model_tf.compile(optimizer='adam',
                 loss='sparse_categorical_crossentropy',
                 metrics=['accuracy'])

In [50]:
#r = model_tf.fit(xtrain, ytrain, epochs=10, validation_data=(xtest, ytest))

Epoch 1/10
15750/15750 ━━━━━━━━━━━━━━━━━━━━ 54s 3ms/step - accuracy: 0.8394 - loss: 0.4842 - val_accuracy: 0.9009 - val_loss: 0.2864
Epoch 2/10
15750/15750 ━━━━━━━━━━━━━━━━━━━━ 47s 3ms/step - accuracy: 0.8965 - loss: 0.2462 - val_accuracy: 0.9132 - val_loss: 0.2073
Epoch 3/10
12321/15750 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - accuracy: 0.9037 - loss: 0.2298

KeyboardInterrupt:

In [ ]:
'''plt.plot(r.history['loss'], label='loss')
plt.plot(r.history['val_loss'], label = 'validation_loss')
plt.legend()'''

In [ ]:
'''plt.plot(r.history['accuracy'], label = 'training_accuracy')
plt.plot(r.history['val_accuracy'], label = 'validation_accuracy')
plt.legend()'''

In [52]:
Final_model = RandomForestClassifier(n_estimators=200)
Final_model.fit(encoded_dataset, y)

RandomForestClassifier(n_estimators=200)

In [53]:
test_dataset = pd.read_csv('/content/test.csv')
id = test_dataset['id']
test_dataset.drop('id', axis = 1)
test_dataset['Mulching_Used'] = test_dataset['Mulching_Used'].map({'No':0, 'Yes':1})
test_dataset = pd.DataFrame(ct.transform(test_dataset), columns=encoded_columns)

In [54]:
test_dataset

,onehotencoder__Soil_Type_Loamy,onehotencoder__Soil_Type_Sandy,onehotencoder__Soil_Type_Silt,onehotencoder__Crop_Type_Maize,onehotencoder__Crop_Type_Potato,onehotencoder__Crop_Type_Rice,onehotencoder__Crop_Type_Sugarcane,onehotencoder__Crop_Type_Wheat,onehotencoder__Crop_Growth_Stage_Harvest,onehotencoder__Crop_Growth_Stage_Sowing,...,remainder__Organic_Carbon,remainder__Electrical_Conductivity,remainder__Temperature_C,remainder__Humidity,remainder__Rainfall_mm,remainder__Sunlight_Hours,remainder__Wind_Speed_kmh,remainder__Field_Area_hectare,remainder__Mulching_Used,remainder__Previous_Irrigation_mm
0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.59,2.81,17.83,30.24,1533.38,5.40,3.00,13.59,1.0,47.48
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.18,3.26,21.18,78.07,576.05,7.22,15.88,6.12,1.0,56.43
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.96,0.85,26.87,60.35,545.30,9.43,2.63,3.11,1.0,20.00
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.83,0.55,41.74,36.05,1211.03,6.69,1.86,2.27,0.0,102.99
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.54,2.11,41.08,52.47,1321.91,4.11,5.71,12.39,1.0,13.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269995,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.68,2.58,33.27,72.09,2326.61,7.09,10.02,2.93,1.0,43.49
269996,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.85,1.04,27.55,45.16,2322.37,5.15,5.62,11.23,1.0,92.03
269997,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.56,1.90,23.39,64.87,996.72,10.44,9.98,2.88,1.0,34.02
269998,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,1.32,2.65,41.09,58.04,1130.71,5.11,1.46,5.71,1.0,3.92
269999,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.41,3.41,35.15,61.30,1270.60,9.69,9.93,4.01,0.0,108.20

In [55]:
predicted_values = Final_model.predict(test_dataset)

In [73]:
pd.Series(predicted_values).map({0:'Low', 1:'Medium', 2:'High'})

0            Low
1            Low
2            Low
3            Low
4            Low
           ...
269995    Medium
269996       Low
269997    Medium
269998       Low
269999    Medium
Length: 270000, dtype: object

In [74]:
submission = pd.DataFrame(
    {'id': id,
     'Irrigation_Need': pd.Series(predicted_values).map({0:'Low', 1:'Medium', 2:'High'})
    }
)
submission.to_csv('submission.csv', index=False)