In [3]:
import numpy as np
import pandas as pd
import torch

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [5]:
df

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,NaN

In [6]:
df.drop(['id', 'Unnamed: 32'], inplace = True, axis = 1)

In [7]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

xtrain, xtest, ytrain, ytest = train_test_split(df.drop(['diagnosis'], axis = 1), df['diagnosis'], test_size=0.2)

In [9]:
ytrain

510    B
299    B
441    M
538    B
462    B
      ..
517    M
230    M
155    B
567    M
71     B
Name: diagnosis, Length: 455, dtype: object

In [10]:
scalar = StandardScaler()
xtrain = scalar.fit_transform(xtrain)
xtest = scalar.transform(xtest)

In [11]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
ytrain = encoder.fit_transform(ytrain)
ytest = encoder.transform(ytest)

In [12]:
ytrain

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0])

In [13]:
xtrain_tensor = torch.from_numpy(xtrain)
xtest_tensor = torch.from_numpy(xtest)
ytrain_tensor = torch.from_numpy(ytrain)
ytest_tensor = torch.from_numpy(ytest)

In [14]:
xtrain_tensor

tensor([[-0.6608, -1.0641, -0.6290,  ..., -0.1361, -0.4889,  0.8093],
        [-1.0096,  0.8714, -1.0186,  ..., -1.2639, -1.0948, -0.8837],
        [ 0.9073,  1.4083,  0.8573,  ...,  0.8999, -0.6561, -0.2468],
        ...,
        [-0.5162, -0.3153, -0.5483,  ..., -0.4925,  0.3291, -0.1442],
        [ 1.8516,  2.3093,  1.9980,  ...,  2.2818,  1.8945,  2.1853],
        [-1.4696, -1.0757, -1.3505,  ..., -1.0120, -1.0514,  1.3338]],
       dtype=torch.float64)

In [30]:
learning_rate = 0.1
epochs = 1000

In [16]:
xtrain_tensor.shape

torch.Size([455, 30])

In [22]:
class SimpleNN():
  def __init__(self, x):
    self.weights = torch.rand(x.shape[1], 1, dtype=torch.float64, requires_grad=True) ## creates a 30x1 matrix
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, x):
    z = torch.matmul(x, self.weights) + self.bias
    return torch.sigmoid(z)

  def binary_cross_entropy(self, y_pred, y):
    EPSILON  = 1e-10
    y_pred = torch.clamp(y_pred, EPSILON, 1-EPSILON)

    loss = -torch.mean(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred))
    return loss

In [31]:
# creating model
model = SimpleNN(xtrain_tensor)
model.weights

tensor([[0.7972],
        [0.2018],
        [0.1265],
        [0.2013],
        [0.0665],
        [0.9680],
        [0.7598],
        [0.6261],
        [0.9518],
        [0.3840],
        [0.8736],
        [0.2892],
        [0.0235],
        [0.6693],
        [0.7934],
        [0.6418],
        [0.4282],
        [0.1107],
        [0.7470],
        [0.6302],
        [0.9368],
        [0.5107],
        [0.9701],
        [0.3871],
        [0.0752],
        [0.5659],
        [0.4900],
        [0.9908],
        [0.0428],
        [0.9053]], dtype=torch.float64, requires_grad=True)

In [24]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [32]:
# define loop
for epoch in range(epochs):
  # forward pass
  y_pred = model.forward(xtrain_tensor)

  # loss calculate
  loss = model.binary_cross_entropy(y_pred, ytrain_tensor)
  print(f'epoch: {epoch+1}, loss: {loss.item()}')
  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  #zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

epoch: 1, loss: 4.233863182382093
epoch: 2, loss: 4.0650145015185215
epoch: 3, loss: 3.88951941038307
epoch: 4, loss: 3.714457779152084
epoch: 5, loss: 3.537973605722409
epoch: 6, loss: 3.357632569696988
epoch: 7, loss: 3.170977389318277
epoch: 8, loss: 2.982908765519824
epoch: 9, loss: 2.7955107355354327
epoch: 10, loss: 2.6062287645373816
epoch: 11, loss: 2.41731684044043
epoch: 12, loss: 2.228632694609302
epoch: 13, loss: 2.0442537671206873
epoch: 14, loss: 1.8630558544556863
epoch: 15, loss: 1.6906581015275193
epoch: 16, loss: 1.5291257869932384
epoch: 17, loss: 1.3807569675654616
epoch: 18, loss: 1.247885339386447
epoch: 19, loss: 1.1325413828520658
epoch: 20, loss: 1.036005709929185
epoch: 21, loss: 0.9583832465844141
epoch: 22, loss: 0.8983962148641059
epoch: 23, loss: 0.8535679795919209
epoch: 24, loss: 0.8207753114797015
epoch: 25, loss: 0.7969047939407291
epoch: 26, loss: 0.7793223193291056
epoch: 27, loss: 0.7660496644111924
epoch: 28, loss: 0.7557167378762198
epoch: 29, loss: 0.7474169151205512
epoch: 30, loss: 0.7405601945002046
epoch: 31, loss: 0.734761363213154
epoch: 32, loss: 0.729764732165379
epoch: 33, loss: 0.7253961189530206
epoch: 34, loss: 0.721532948634399
epoch: 35, loss: 0.7180858654843179
epoch: 36, loss: 0.7149874662300086
epoch: 37, loss: 0.7121853511797666
epoch: 38, loss: 0.709637760286807
epoch: 39, loss: 0.707310753186407
epoch: 40, loss: 0.7051763205717247
epoch: 41, loss: 0.7032110697739241
epoch: 42, loss: 0.7013952758104688
epoch: 43, loss: 0.6997121740638411
epoch: 44, loss: 0.6981474191623154
epoch: 45, loss: 0.6966886624755207
epoch: 46, loss: 0.6953252169767009
epoch: 47, loss: 0.6940477881108934
epoch: 48, loss: 0.692848255524367
epoch: 49, loss: 0.6917194945845219
epoch: 50, loss: 0.6906552293991556
epoch: 51, loss: 0.6896499110093268
epoch: 52, loss: 0.688698615860605
epoch: 53, loss: 0.6877969607226224
epoch: 54, loss: 0.686941031033598
epoch: 55, loss: 0.6861273202655229
epoch: 56, loss: 0.6853526783854338
epoch: 57, loss: 0.6846142678630488
epoch: 58, loss: 0.6839095259698653
epoch: 59, loss: 0.683236132348163
epoch: 60, loss: 0.6825919810140318
epoch: 61, loss: 0.6819751561070777
epoch: 62, loss: 0.6813839108188822
epoch: 63, loss: 0.680816649028792
epoch: 64, loss: 0.6802719092539449
epoch: 65, loss: 0.6797483505843603
epoch: 66, loss: 0.679244740326293
epoch: 67, loss: 0.678759943120166
epoch: 68, loss: 0.6782929113350599
epoch: 69, loss: 0.6778426765713503
epoch: 70, loss: 0.6774083421277728
epoch: 71, loss: 0.6769890763098844
epoch: 72, loss: 0.676584106474267
epoch: 73, loss: 0.6761927137174835
epoch: 74, loss: 0.675814228131223
epoch: 75, loss: 0.6754480245556097
epoch: 76, loss: 0.675093518771657
epoch: 77, loss: 0.6747501640815292
epoch: 78, loss: 0.6744174482318644
epoch: 79, loss: 0.6740948906410871
epoch: 80, loss: 0.6737820398965199
epoch: 81, loss: 0.6734784714913258
epoch: 82, loss: 0.6731837857749715
epoch: 83, loss: 0.672897606094072
epoch: 84, loss: 0.6726195771032374
epoch: 85, loss: 0.6723493632279479
epoch: 86, loss: 0.6720866472635758
epoch: 87, loss: 0.6718311290965151
epoch: 88, loss: 0.6715825245349767
epoch: 89, loss: 0.6713405642384209
epoch: 90, loss: 0.6711049927358327
epoch: 91, loss: 0.6708755675241292
epoch: 92, loss: 0.6706520582389542
epoch: 93, loss: 0.6704342458909435
epoch: 94, loss: 0.6702219221613052
epoch: 95, loss: 0.6700148887512023
epoch: 96, loss: 0.6698129567800123
epoch: 97, loss: 0.6696159462280561
epoch: 98, loss: 0.6694236854198353
epoch: 99, loss: 0.6692360105442305
epoch: 100, loss: 0.6690527652084673
epoch: 101, loss: 0.6688738000229753
epoch: 102, loss: 0.6686989722145532
epoch: 103, loss: 0.6685281452655052
epoch: 104, loss: 0.6683611885766332
epoch: 105, loss: 0.6681979771521799
epoch: 106, loss: 0.6680383913049937
epoch: 107, loss: 0.6678823163803425
epoch: 108, loss: 0.6677296424969572
epoch: 109, loss: 0.6675802643040053
epoch: 110, loss: 0.6674340807528162
epoch: 111, loss: 0.667290994882284
epoch: 112, loss: 0.6671509136169629
epoch: 113, loss: 0.6670137475769597
epoch: 114, loss: 0.666879410898799
epoch: 115, loss: 0.6667478210665094
epoch: 116, loss: 0.6666188987522392
epoch: 117, loss: 0.6664925676657616
epoch: 118, loss: 0.6663687544122922
epoch: 119, loss: 0.6662473883580703
epoch: 120, loss: 0.6661284015032158
epoch: 121, loss: 0.6660117283613931
epoch: 122, loss: 0.6658973058458667
epoch: 123, loss: 0.6657850731615452
epoch: 124, loss: 0.6656749717026577
epoch: 125, loss: 0.6655669449557176
epoch: 126, loss: 0.6654609384074636
epoch: 127, loss: 0.6653568994574811
epoch: 128, loss: 0.6652547773352372
epoch: 129, loss: 0.6651545230212701
epoch: 130, loss: 0.6650560891722986
epoch: 131, loss: 0.6649594300500309
epoch: 132, loss: 0.6648645014534653
epoch: 133, loss: 0.6647712606544877
epoch: 134, loss: 0.6646796663365888
epoch: 135, loss: 0.664589678536528
epoch: 136, loss: 0.6645012585887852
epoch: 137, loss: 0.664414369072653
epoch: 138, loss: 0.6643289737618276
epoch: 139, loss: 0.6642450375763661
epoch: 140, loss: 0.6641625265368881
epoch: 141, loss: 0.6640814077209024
epoch: 142, loss: 0.6640016492211512
epoch: 143, loss: 0.6639232201058672
epoch: 144, loss: 0.663846090380847
epoch: 145, loss: 0.6637702309532438
epoch: 146, loss: 0.6636956135970029
epoch: 147, loss: 0.6636222109198455
epoch: 148, loss: 0.6635499963317328
epoch: 149, loss: 0.663478944014733
epoch: 150, loss: 0.6634090288942212
epoch: 151, loss: 0.6633402266113501
epoch: 152, loss: 0.6632725134967259
epoch: 153, loss: 0.6632058665452325
epoch: 154, loss: 0.6631402633919484
epoch: 155, loss: 0.6630756822891036
epoch: 156, loss: 0.6630121020840255
epoch: 157, loss: 0.6629495021980283
epoch: 158, loss: 0.6628878626061996
epoch: 159, loss: 0.6628271638180427
epoch: 160, loss: 0.6627673868589328
epoch: 161, loss: 0.6627085132523504
epoch: 162, loss: 0.6626505250028549
epoch: 163, loss: 0.6625934045797643
epoch: 164, loss: 0.6625371349015063
epoch: 165, loss: 0.6624816993206128
epoch: 166, loss: 0.6624270816093252
epoch: 167, loss: 0.6623732659457856
epoch: 168, loss: 0.6623202369007827
epoch: 169, loss: 0.6622679794250321
epoch: 170, loss: 0.6622164788369636
epoch: 171, loss: 0.6621657208109921
epoch: 172, loss: 0.6621156913662533
epoch: 173, loss: 0.6620663768557803
epoch: 174, loss: 0.6620177639561037
epoch: 175, loss: 0.6619698396572534
epoch: 176, loss: 0.6619225912531489
epoch: 177, loss: 0.6618760063323548
epoch: 178, loss: 0.6618300727691911
epoch: 179, loss: 0.6617847787151806
epoch: 180, loss: 0.6617401125908154
epoch: 181, loss: 0.6616960630776358
epoch: 182, loss: 0.6616526191105997
epoch: 183, loss: 0.6616097698707376
epoch: 184, loss: 0.6615675047780744
epoch: 185, loss: 0.6615258134848127
epoch: 186, loss: 0.6614846858687593
epoch: 187, loss: 0.6614441120269929
epoch: 188, loss: 0.6614040822697544
epoch: 189, loss: 0.6613645871145577
epoch: 190, loss: 0.6613256172805058
epoch: 191, loss: 0.661287163682808
epoch: 192, loss: 0.661249217427488
epoch: 193, loss: 0.6612117698062734
epoch: 194, loss: 0.6611748122916626
epoch: 195, loss: 0.6611383365321596
epoch: 196, loss: 0.6611023343476692
epoch: 197, loss: 0.6610667977250487
epoch: 198, loss: 0.6610317188138064
epoch: 199, loss: 0.6609970899219441
epoch: 200, loss: 0.6609629035119359
epoch: 201, loss: 0.6609291521968379
epoch: 202, loss: 0.6608958287365247
epoch: 203, loss: 0.6608629260340481
epoch: 204, loss: 0.6608304371321087
epoch: 205, loss: 0.6607983552096438
epoch: 206, loss: 0.66076667357852
epoch: 207, loss: 0.6607353856803292
epoch: 208, loss: 0.6607044850832847
epoch: 209, loss: 0.6606739654792134
epoch: 210, loss: 0.6606438206806389
epoch: 211, loss: 0.660614044617952
epoch: 212, loss: 0.660584631336669
epoch: 213, loss: 0.6605555749947707
epoch: 214, loss: 0.6605268698601179
epoch: 215, loss: 0.660498510307947
epoch: 216, loss: 0.6604704908184356
epoch: 217, loss: 0.6604428059743394
epoch: 218, loss: 0.6604154504586978
epoch: 219, loss: 0.6603884190526035
epoch: 220, loss: 0.6603617066330364
epoch: 221, loss: 0.6603353081707578
epoch: 222, loss: 0.6603092187282629
epoch: 223, loss: 0.6602834334577911
epoch: 224, loss: 0.6602579475993889
epoch: 225, loss: 0.660232756479028
epoch: 226, loss: 0.6602078555067723
epoch: 227, loss: 0.6601832401749953
epoch: 228, loss: 0.660158906056643
epoch: 229, loss: 0.6601348488035462
epoch: 230, loss: 0.6601110641447738
epoch: 231, loss: 0.6600875478850299
epoch: 232, loss: 0.660064295903093
epoch: 233, loss: 0.6600413041502952
epoch: 234, loss: 0.6600185686490389
epoch: 235, loss: 0.6599960854913521
epoch: 236, loss: 0.6599738508374806
epoch: 237, loss: 0.6599518609145127
epoch: 238, loss: 0.6599301120150409
epoch: 239, loss: 0.6599086004958549
epoch: 240, loss: 0.6598873227766663
epoch: 241, loss: 0.6598662753388657
epoch: 242, loss: 0.6598454547243073
epoch: 243, loss: 0.6598248575341259
epoch: 244, loss: 0.6598044804275778
epoch: 245, loss: 0.6597843201209131
epoch: 246, loss: 0.6597643733862723
epoch: 247, loss: 0.6597446370506074
epoch: 248, loss: 0.6597251079946321
epoch: 249, loss: 0.6597057831517911
epoch: 250, loss: 0.6596866595072568
epoch: 251, loss: 0.6596677340969468
epoch: 252, loss: 0.6596490040065642
epoch: 253, loss: 0.6596304663706594
epoch: 254, loss: 0.6596121183717124
epoch: 255, loss: 0.6595939572392361
epoch: 256, loss: 0.6595759802488991
epoch: 257, loss: 0.6595581847216675
epoch: 258, loss: 0.659540568022965
epoch: 259, loss: 0.6595231275618528
epoch: 260, loss: 0.6595058607902256
epoch: 261, loss: 0.6594887652020248
epoch: 262, loss: 0.6594718383324697
epoch: 263, loss: 0.6594550777573039
epoch: 264, loss: 0.6594384810920584
epoch: 265, loss: 0.659422045991329
epoch: 266, loss: 0.6594057701480708
epoch: 267, loss: 0.6593896512929039
epoch: 268, loss: 0.6593736871934386
epoch: 269, loss: 0.6593578756536083
epoch: 270, loss: 0.6593422145130221
epoch: 271, loss: 0.6593267016463261
epoch: 272, loss: 0.6593113349625799
epoch: 273, loss: 0.6592961124046446
epoch: 274, loss: 0.6592810319485848
epoch: 275, loss: 0.6592660916030804
epoch: 276, loss: 0.6592512894088509
epoch: 277, loss: 0.6592366234380928
epoch: 278, loss: 0.6592220917939251
epoch: 279, loss: 0.6592076926098485
epoch: 280, loss: 0.6591934240492134
epoch: 281, loss: 0.6591792843046993
epoch: 282, loss: 0.6591652715978036
epoch: 283, loss: 0.659151384178341
epoch: 284, loss: 0.6591376203239517
epoch: 285, loss: 0.6591239783396213
epoch: 286, loss: 0.6591104565572057
epoch: 287, loss: 0.6590970533349699
epoch: 288, loss: 0.6590837670571323
epoch: 289, loss: 0.6590705961334186
epoch: 290, loss: 0.6590575389986244
epoch: 291, loss: 0.6590445941121863
epoch: 292, loss: 0.6590317599577603
epoch: 293, loss: 0.6590190350428082
epoch: 294, loss: 0.6590064178981926
epoch: 295, loss: 0.6589939070777786
epoch: 296, loss: 0.6589815011580432
epoch: 297, loss: 0.6589691987376916
epoch: 298, loss: 0.6589569984372812
epoch: 299, loss: 0.6589448988988528
epoch: 300, loss: 0.6589328987855665
epoch: 301, loss: 0.6589209967813476
epoch: 302, loss: 0.6589091915905363
epoch: 303, loss: 0.658897481937544
epoch: 304, loss: 0.6588858665665178
epoch: 305, loss: 0.6588743442410093
epoch: 306, loss: 0.6588629137436497
epoch: 307, loss: 0.6588515738758313
epoch: 308, loss: 0.6588403234573941
epoch: 309, loss: 0.6588291613263193
epoch: 310, loss: 0.6588180863384255
epoch: 311, loss: 0.6588070973670749
epoch: 312, loss: 0.6587961933028795
epoch: 313, loss: 0.6587853730534168
epoch: 314, loss: 0.6587746355429484
epoch: 315, loss: 0.6587639797121433
epoch: 316, loss: 0.6587534045178086
epoch: 317, loss: 0.6587429089326214
epoch: 318, loss: 0.658732491944869
epoch: 319, loss: 0.6587221525581906
epoch: 320, loss: 0.6587118897913254
epoch: 321, loss: 0.6587017026778651
epoch: 322, loss: 0.6586915902660099
epoch: 323, loss: 0.6586815516183291
epoch: 324, loss: 0.6586715858115261
epoch: 325, loss: 0.658661691936207
epoch: 326, loss: 0.6586518690966546
epoch: 327, loss: 0.658642116410604
epoch: 328, loss: 0.6586324330090241
epoch: 329, loss: 0.6586228180359027
epoch: 330, loss: 0.6586132706480335
epoch: 331, loss: 0.6586037900148097
epoch: 332, loss: 0.658594375318018
epoch: 333, loss: 0.6585850257516394
epoch: 334, loss: 0.6585757405216498
epoch: 335, loss: 0.6585665188458278
epoch: 336, loss: 0.6585573599535633
epoch: 337, loss: 0.6585482630856694
epoch: 338, loss: 0.6585392274941995
epoch: 339, loss: 0.658530252442265
epoch: 340, loss: 0.6585213372038581
epoch: 341, loss: 0.6585124810636769
epoch: 342, loss: 0.6585036833169524
epoch: 343, loss: 0.6584949432692809
epoch: 344, loss: 0.6584862602364568
epoch: 345, loss: 0.6584776335443102
epoch: 346, loss: 0.6584690625285452
epoch: 347, loss: 0.6584605465345826
epoch: 348, loss: 0.658452084917405
epoch: 349, loss: 0.6584436770414043
epoch: 350, loss: 0.6584353222802306
epoch: 351, loss: 0.6584270200166463
epoch: 352, loss: 0.6584187696423801
epoch: 353, loss: 0.6584105705579846
epoch: 354, loss: 0.6584024221726968
epoch: 355, loss: 0.6583943239042995
epoch: 356, loss: 0.6583862751789864
epoch: 357, loss: 0.6583782754312282
epoch: 358, loss: 0.6583703241036432
epoch: 359, loss: 0.6583624206468663
epoch: 360, loss: 0.6583545645194245
epoch: 361, loss: 0.6583467551876104
epoch: 362, loss: 0.6583389921253618
epoch: 363, loss: 0.65833127481414
epoch: 364, loss: 0.6583236027428113
epoch: 365, loss: 0.6583159754075313
epoch: 366, loss: 0.6583083923116304
epoch: 367, loss: 0.6583008529655002
epoch: 368, loss: 0.6582933568864843
epoch: 369, loss: 0.658285903598768
epoch: 370, loss: 0.6582784926332723
epoch: 371, loss: 0.658271123527548
epoch: 372, loss: 0.6582637958256718
epoch: 373, loss: 0.6582565090781457
epoch: 374, loss: 0.6582492628417954
epoch: 375, loss: 0.6582420566796727
epoch: 376, loss: 0.6582348901609583
epoch: 377, loss: 0.6582277628608662
epoch: 378, loss: 0.6582206743605508
epoch: 379, loss: 0.6582136242470135
epoch: 380, loss: 0.6582066121130132
epoch: 381, loss: 0.6581996375569765
epoch: 382, loss: 0.6581927001829098
epoch: 383, loss: 0.6581857996003131
epoch: 384, loss: 0.6581789354240957
epoch: 385, loss: 0.6581721072744918
epoch: 386, loss: 0.6581653147769796
epoch: 387, loss: 0.6581585575621985
epoch: 388, loss: 0.6581518352658718
epoch: 389, loss: 0.6581451475287273
epoch: 390, loss: 0.6581384939964208
epoch: 391, loss: 0.6581318743194599
epoch: 392, loss: 0.6581252881531304
epoch: 393, loss: 0.6581187351574224
epoch: 394, loss: 0.6581122149969586
epoch: 395, loss: 0.658105727340924
epoch: 396, loss: 0.6580992718629947
epoch: 397, loss: 0.6580928482412705
epoch: 398, loss: 0.6580864561582074
epoch: 399, loss: 0.658080095300551
epoch: 400, loss: 0.6580737653592711
epoch: 401, loss: 0.658067466029497
epoch: 402, loss: 0.6580611970104558
epoch: 403, loss: 0.6580549580054084
epoch: 404, loss: 0.6580487487215898
epoch: 405, loss: 0.658042568870148
epoch: 406, loss: 0.6580364181660849
epoch: 407, loss: 0.6580302963281981
epoch: 408, loss: 0.6580242030790243
epoch: 409, loss: 0.6580181381447815
epoch: 410, loss: 0.6580121012553144
epoch: 411, loss: 0.6580060921440396
epoch: 412, loss: 0.6580001105478919
epoch: 413, loss: 0.6579941562072711
epoch: 414, loss: 0.6579882288659907
epoch: 415, loss: 0.6579823282712258
epoch: 416, loss: 0.6579764541734632
epoch: 417, loss: 0.6579706063264517
epoch: 418, loss: 0.6579647844871537
epoch: 419, loss: 0.657958988415696
epoch: 420, loss: 0.6579532178753246
epoch: 421, loss: 0.6579474726323559
epoch: 422, loss: 0.6579417524561327
epoch: 423, loss: 0.6579360571189785
epoch: 424, loss: 0.6579303863961529
epoch: 425, loss: 0.6579247400658085
epoch: 426, loss: 0.6579191179089479
epoch: 427, loss: 0.6579135197093811
epoch: 428, loss: 0.6579079452536845
epoch: 429, loss: 0.6579023943311598
epoch: 430, loss: 0.6578968667337931
epoch: 431, loss: 0.6578913622562164
epoch: 432, loss: 0.6578858806956678
epoch: 433, loss: 0.6578804218519535
epoch: 434, loss: 0.6578749855274099
epoch: 435, loss: 0.6578695715268661
epoch: 436, loss: 0.6578641796576077
epoch: 437, loss: 0.6578588097293416
epoch: 438, loss: 0.6578534615541585
epoch: 439, loss: 0.6578481349464999
epoch: 440, loss: 0.6578428297231226
epoch: 441, loss: 0.657837545703066
epoch: 442, loss: 0.6578322827076175
epoch: 443, loss: 0.6578270405602812
epoch: 444, loss: 0.657821819086744
epoch: 445, loss: 0.6578166181148453
epoch: 446, loss: 0.6578114374745456
epoch: 447, loss: 0.6578062769978946
epoch: 448, loss: 0.6578011365190028
epoch: 449, loss: 0.6577960158740095
epoch: 450, loss: 0.6577909149010553
epoch: 451, loss: 0.6577858334402528
epoch: 452, loss: 0.6577807713336569
epoch: 453, loss: 0.6577757284252396
epoch: 454, loss: 0.657770704560859
epoch: 455, loss: 0.6577656995882348
epoch: 456, loss: 0.6577607133569208
epoch: 457, loss: 0.6577557457182784
epoch: 458, loss: 0.6577507965254508
epoch: 459, loss: 0.6577458656333378
epoch: 460, loss: 0.6577409528985704
epoch: 461, loss: 0.6577360581794864
epoch: 462, loss: 0.6577311813361063
epoch: 463, loss: 0.6577263222301082
epoch: 464, loss: 0.657721480724806
epoch: 465, loss: 0.6577166566851248
epoch: 466, loss: 0.6577118499775788
epoch: 467, loss: 0.6577070604702486
epoch: 468, loss: 0.6577022880327588
epoch: 469, loss: 0.6576975325362566
epoch: 470, loss: 0.6576927938533905
epoch: 471, loss: 0.6576880718582884
epoch: 472, loss: 0.6576833664265377
epoch: 473, loss: 0.6576786774351641
epoch: 474, loss: 0.6576740047626116
epoch: 475, loss: 0.657669348288723
epoch: 476, loss: 0.6576647078947203
epoch: 477, loss: 0.6576600834631847
epoch: 478, loss: 0.6576554748780384
epoch: 479, loss: 0.6576508820245262
epoch: 480, loss: 0.6576463047891955
epoch: 481, loss: 0.6576417430598803
epoch: 482, loss: 0.6576371967256818
epoch: 483, loss: 0.6576326656769517
epoch: 484, loss: 0.6576281498052742
epoch: 485, loss: 0.6576236490034499
epoch: 486, loss: 0.6576191631654781
epoch: 487, loss: 0.6576146921865406
epoch: 488, loss: 0.657610235962986
epoch: 489, loss: 0.6576057943923128
epoch: 490, loss: 0.6576013673731539
epoch: 491, loss: 0.6575969548052614
epoch: 492, loss: 0.657592556589491
epoch: 493, loss: 0.6575881726277871
epoch: 494, loss: 0.6575838028231676
epoch: 495, loss: 0.6575794470797095
epoch: 496, loss: 0.6575751053025347
epoch: 497, loss: 0.6575707773977955
epoch: 498, loss: 0.6575664632726606
epoch: 499, loss: 0.6575621628353021
epoch: 500, loss: 0.6575578759948805
epoch: 501, loss: 0.6575536026615325
epoch: 502, loss: 0.6575493427463576
epoch: 503, loss: 0.6575450961614053
epoch: 504, loss: 0.6575408628196616
epoch: 505, loss: 0.6575366426350369
epoch: 506, loss: 0.6575324355223543
epoch: 507, loss: 0.6575282413973363
epoch: 508, loss: 0.6575240601765927
epoch: 509, loss: 0.6575198917776105
epoch: 510, loss: 0.65751573611874
epoch: 511, loss: 0.6575115931191848
epoch: 512, loss: 0.6575074626989901
epoch: 513, loss: 0.657503344779031
epoch: 514, loss: 0.6574992392810022
epoch: 515, loss: 0.6574951461274072
epoch: 516, loss: 0.6574910652415473
epoch: 517, loss: 0.6574869965475109
epoch: 518, loss: 0.6574829399701637
epoch: 519, loss: 0.6574788954351385
epoch: 520, loss: 0.6574748628688242
epoch: 521, loss: 0.657470842198357
epoch: 522, loss: 0.6574668333516107
epoch: 523, loss: 0.657462836257186
epoch: 524, loss: 0.6574588508444015
epoch: 525, loss: 0.6574548770432855
epoch: 526, loss: 0.6574509147845651
epoch: 527, loss: 0.6574469639996576
epoch: 528, loss: 0.6574430246206631
epoch: 529, loss: 0.657439096580353
epoch: 530, loss: 0.657435179812164
epoch: 531, loss: 0.6574312742501879
epoch: 532, loss: 0.6574273798291634
epoch: 533, loss: 0.6574234964844683
epoch: 534, loss: 0.6574196241521113
epoch: 535, loss: 0.6574157627687233
epoch: 536, loss: 0.6574119122715506
epoch: 537, loss: 0.6574080725984454
epoch: 538, loss: 0.6574042436878594
epoch: 539, loss: 0.6574004254788369
epoch: 540, loss: 0.6573966179110049
epoch: 541, loss: 0.6573928209245674
epoch: 542, loss: 0.6573890344602987
epoch: 543, loss: 0.6573852584595344
epoch: 544, loss: 0.6573814928641657
epoch: 545, loss: 0.657377737616632

In [33]:
#model evaluation
with torch.no_grad():
  y_pred = model.forward(xtest_tensor)
  y_pred = (y_pred > 0.5).float()

In [34]:
accuracy = (y_pred == ytest_tensor).float().mean()
print(accuracy)

tensor(0.5877)